---
title: "Linear Dynamic Range"
output: html_document
date: "2026-02-03"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)
library(ggpmisc)
library(gridExtra)
```

```{r}
setwd("C:/Users/erbye/OneDrive - The Pennsylvania State University/Data/Thesis Studies/")
range <- read.csv("WB Linear Dynamic Range.csv")
```

```{r}
# Separate into 2 data frames - one for targets and one for total protein
tp1 <- range[range$Target == "Total Protein", ]
targets <- range[range$Target != "Total Protein", ]
```

```{r}
# Create 2 additional data frames for total protein excluding 30 ug and then 30 and 0.46875 ug
tp2 <- tp1[1:6, ]
tp3 <- tp1[2:6, ]
```

```{r}
g1 <- ggplot(tp1, aes(x = Protein.Load, y = Relative.Intensity)) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
  geom_smooth(method = "lm", se = F) +
  stat_poly_eq(use_label(c("eq", "R2"))) +
  labs(y = "Relative Intensity", x = expression(paste("Protein Load (", mu, "g)"))) +
  theme(text = element_text(color = "black"),
        axis.text = element_text(color = "black", size = 10),
        axis.title = element_text(size = 14),
        legend.position = "none",
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"))
g2 <- ggplot(tp2, aes(x = Protein.Load, y = Relative.Intensity)) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
  geom_smooth(method = "lm", se = F) +
  stat_poly_eq(use_label(c("eq", "R2"))) +
  labs(y = "Relative Intensity", x = expression(paste("Protein Load (", mu, "g)"))) +
  theme(text = element_text(color = "black"),
        axis.text = element_text(color = "black", size = 10),
        axis.title = element_text(size = 14),
        legend.position = "none",
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"))
g3 <- ggplot(tp3, aes(x = Protein.Load, y = Relative.Intensity)) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
  geom_smooth(method = "lm", se = F) +
  stat_poly_eq(use_label(c("eq", "R2"))) +
  labs(y = "Relative Intensity", x = expression(paste("Protein Load (", mu, "g)"))) +
  theme(text = element_text(color = "black"),
        axis.text = element_text(color = "black", size = 10),
        axis.title = element_text(size = 14),
        legend.position = "none",
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"))
```

```{r}
grid.arrange(g1, g2, g3, ncol = 3)
```

```{r}
targets$Target <- gsub(pattern = "a-Actinin", replacement = "\U03B1-Actinin", x = targets$Target)
targets$Target <- gsub(pattern = "a-Tubulin", replacement = "\U03B1-Tubulin", x = targets$Target)
targets$Target <- gsub(pattern = "b-Actin", replacement = "\U03B2-Actin", x = targets$Target)
```

```{r}
targets$Target <- factor(targets$Target, levels = c("\U03B1-Actinin", "\U03B1-Tubulin", "\U03B2-Actin", "Ezrin", "Pan-Cadherin", "Vinculin"))
```

```{r}
ggplot(targets, aes(x = Protein.Load, y = Relative.Intensity, color = Target)) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
  # geom_smooth(method = "lm", se = F) +
  # stat_poly_eq(use_label(c("eq", "R2"))) +
  scale_color_manual(values = c("#918665", "#90C226", "#54A021", "#E6B91E", "#E76618", "#C42F1A")) +
  labs(y = "Relative Intensity", x = expression(paste("Protein Load (", mu, "g)"))) +
  theme(text = element_text(color = "black"),
        axis.text = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 14),
        legend.position = "right",
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12, face = "bold"),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"))
```

```{r}
no30 <- targets[targets$Protein.Load != 0.46875 & targets$Protein.Load != 30, ]
```

```{r}
ggplot(no30, aes(x = Protein.Load, y = Relative.Intensity, color = Target)) +
  geom_point(size = 3) +
  # geom_line(linewidth = 1) +
  geom_smooth(method = "lm", se = F) +
  stat_poly_eq(use_label(c("eq", "R2"))) +
  scale_color_manual(values = c("#918665", "#90C226", "#54A021", "#E6B91E", "#E76618", "#C42F1A")) +
  labs(y = "Relative Intensity", x = expression(paste("Protein Load (", mu, "g)"))) +
  theme(text = element_text(color = "black"),
        axis.text = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 14),
        legend.position = "none",
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"))
```

